windowrule {
    name = rebuild-rules
    match:class = ^(rebuild)$
    float = yes
    size = 900 500
    center = yes
}

windowrule {
    name = firefox-workspace
    match:class = ^(firefox)$
    workspace = 1
}

windowrule {
    name = kitty-workspace
    match:class = ^(kitty)$
    workspace = 3
}

windowrule {
    name = lf-workspace
    match:class = ^(lf)$
    workspace = 2
}

windowrule {
    name = neomutt-workspace
    match:class = ^(neomutt)$
    workspace = 4
}

windowrule {
    name = telegram-workspace
    match:class = ^(org.telegram.desktop)$
    workspace = 6
}

windowrule {
    name = jetbrains-workspace
    match:class = ^(jetbrains-.*)$
    workspace = 8
}

windowrule {
    name = vscode-workspace
    match:class = ^(code)$
    workspace = 8
}

windowrule {
    name = slack-workspace
    match:class = ^(Slack)$
    workspace = 9
}

windowrule {
    name = mpv-float
    match:class = ^(mpv)$
    float = yes
}

windowrule {
    name = discord-workspace
    match:class = ^(discord)$
    workspace = 17
}

windowrule {
    name = obsidian-workspace
    match:class = ^(obsidian)$
    workspace = 41
}

windowrule {
    name = zapzap-workspace
    match:class = ^(ZapZap)$
    workspace = 5
}

windowrule {
    name = steam-workspace
    match:class = ^(steam)$
    workspace = 15
}

windowrule {
    name = games-workspace
    match:class = ^(steam_app.*)$
    workspace = 9
}

windowrule {
    name = galculator-float
    match:class = ^(galculator)$
    float = yes
}

windowrule {
    name = zenity-float
    match:class = ^(zenity)$
    float = yes
    pin = yes
}

windowrule {
    name = filemanager-workspace
    match:class = ^(nnn|ranger|Thunar)$
    workspace = 3
}

windowrule {
    name = graphics-workspace
    match:class = ^(pinta|Gimp)$
    workspace = 7
}

windowrule {
    name = database-workspace
    match:class = ^(mysql-workbench|MongoDB Compass|beekeeper-studio)$
    workspace = 11
}

windowrule {
    name = email-workspace
    match:class = ^(thunderbird|Geary)$
    workspace = 12
}

windowrule {
    name = api-workspace
    match:class = ^(Postman|bruno)$
    workspace = 13
}

windowrule {
    name = tradingview-workspace
    match:class = ^(TradingView|tradingview)$
    workspace = 18
}

windowrule {
    name = zathura-workspace
    match:class = ^(org.pwmt.zathura|Zathura)$
    workspace = 19
}

windowrule {
    name = libreoffice-workspace
    match:class = ^(libreoffice.*)$
    workspace = 21
}

windowrule {
    name = recording-workspace
    match:class = ^(com.obsproject.Studio|simplescreenrecorder)$
    workspace = 23
}

windowrule {
    name = torrents-workspace
    match:class = ^(transmission-gtk|qBittorrent)$
    workspace = 26
}

windowrule {
    name = spotify-workspace
    match:class = ^(Spotify|spotify)$
    workspace = 27
}

windowrule {
    name = cursor-workspace
    match:class = ^(Cursor|cursor)$
    workspace = 28
}

windowrule {
    name = minecraft-workspace
    match:class = ^(Minecraft.*)$
    workspace = 9
}

windowrule {
    name = kmag-float
    match:class = ^(kmag)$
    float = yes
    pin = yes
    size = 400 300
}

windowrule {
    name = matplotlib-float
    match:class = ^(matplotlib)$
    float = yes
    pin = yes
}

windowrule {
    name = tmux-float
    match:class = ^(tmux-float)$
    float = yes
    size = 900 500
    center = yes
}
