[mvrozanti@hotmail.com]
source                = notmuch://~/.local/share/mail
maildir-store         = ~/.local/share/mail
maildir-account-path  = mvrozanti@hotmail.com
multi-file-strategy   = act-all
exclude-tags          = deleted,spam
query-map             = ~/.config/aerc/notmuch-query-map
outgoing              = msmtp -a mvrozanti@hotmail.com
default               = INBOX
from                  = Marcelo Vironda Rozanti <mvrozanti@hotmail.com>
copy-to               = Sent
postpone              = Drafts
folders               = INBOX,Junk,Drafts,Sent,Deleted,Archive,Itaú,Sys4bank,Governo,Investimentos,Notes,SRM,NTT Data|C6,Pessoal,Compras,Sent Items,Trash,Unread,Flagged,Recent
folders-sort          = INBOX,Junk,Drafts,Sent,Deleted,Archive,Itaú,Sys4bank,Governo,Investimentos,Notes,SRM,NTT Data|C6,Pessoal,Compras,Sent Items,Trash,Unread,Flagged,Recent
