[mvrozanti@hotmail.com]
source        = maildir://~/.local/share/mail/mvrozanti@hotmail.com
outgoing      = msmtp -a mvrozanti@hotmail.com
default       = INBOX
from          = Marcelo Vironda Rozanti <mvrozanti@hotmail.com>
copy-to       = Sent
postpone      = Drafts
folders       = INBOX,Junk,Drafts,Sent,Deleted,Archive,Itaú,Sys4bank,Conversation History,Governo,Investimentos,Notes,SRM,NTT Data|C6,Pessoal,Compras,Sent Items,mvrozanti,Trash
folders-sort  = INBOX,Junk,Drafts,Sent,Deleted,Archive,Itaú,Sys4bank,Conversation History,Governo,Investimentos,Notes,SRM,NTT Data|C6,Pessoal,Compras,Sent Items,mvrozanti,Trash
