[mvrozanti@hotmail.com]
source        = maildir://~/.local/share/mail/mvrozanti@hotmail.com
outgoing      = msmtp -a mvrozanti@hotmail.com
default       = INBOX
from          = Marcelo Vironda Rozanti <mvrozanti@hotmail.com>
copy-to       = Sent
postpone      = Drafts
