[general]
default-save-path = ~/Downloads

[ui]
sidebar-width        = 24
timestamp-format     = 2006-01-02 15:04
this-day-time-format = 15:04
this-week-time-format = Mon 15:04
this-year-time-format = Jan 02
threading-enabled    = true
dirlist-tree         = true
dirlist-collapse     = 1

[viewer]
pager        = less -R
alternatives = text/plain,text/html

[compose]
editor = nvim

[filters]
text/plain = colorize
text/html  = html
text/*     = bat -fP --style=plain
message/rfc822 = colorize
