[general]
default-save-path    = ~/Downloads
unsafe-accounts-conf = true

[ui]
styleset-name        = catppuccin
sidebar-width        = 26
timestamp-format     = 2006-01-02 15:04
this-day-time-format = 15:04
this-week-time-format = Mon 15:04
this-year-time-format = Jan 02
threading-enabled    = true
dirlist-tree         = true
dirlist-collapse     = 1

icon-new              =
icon-old              =
icon-replied          =
icon-forwarded        =
icon-attachment       =
icon-flagged          =
icon-marked           =
icon-deleted          =
icon-draft            =
icon-unencrypted      =
icon-encrypted        =
icon-signed           =
icon-signed-encrypted =
icon-unknown          =
icon-invalid          =

spinner          = ⣾,⣽,⣻,⢿,⡿,⣟,⣯,⣷
spinner-interval = 100ms

index-columns    = flags:4,name<20%,subject,date>=
column-flags     = {{.Flags | join " "}}
column-name      = {{index (.From | names) 0}}
column-subject   = {{.ThreadPrefix}}{{.Subject}}
column-date      = {{.DateAutoFormat .Date.Local}}

dirlist-left  = {{if eq .Folder "INBOX"}}{{else if eq .Folder "Sent"}}󰒊{{else if eq .Folder "Sent Items"}}󰒊{{else if eq .Folder "Drafts"}}{{else if eq .Folder "Trash"}}{{else if eq .Folder "Deleted"}}{{else if eq .Folder "Junk"}}{{else if eq .Folder "Archive"}}󰮏{{else if eq .Folder "Notes"}}{{else}}{{end}}  {{.Folder | trimPath}}
dirlist-right = {{if .Unread}}{{humanReadable .Unread}}{{end}}

tab-title-account = {{.Account}}{{if .Unread}}  {{.Unread}}{{end}}

[viewer]
pager        = less -R
alternatives = text/plain,text/html

[compose]
editor = nvim

[filters]
text/plain = colorize
text/html  = html
text/*     = bat -fP --style=plain
message/rfc822 = colorize
