#!/bin/sh
# Press C-x to activate to key handler!
while read file
do
        case "$1" in
        "y")
                xclip -selection clipboard "$file" -t image/jpeg
                ;;
        "w")
                /home/m/.local/bin/setbg "$file"
                ;;
        esac
done
