#!/bin/sh
# Press C-x to activate to key handler!

while read file
do
        case "$1" in
        "y")
                ic "$file"
                notify-send 'Copied to clipboard'
                ;;
        "w")
                $HOME/.local/bin/setbg "$file"
                ;;
        esac
done
