#!/bin/sh
# Press C-x to activate to key handler!

while read file
do
        case "$1" in
        "y")
                ic "$file"
                notify-send 'Copied to clipboard'
                ;;
        "w")
                $HOME/.local/bin/setbg "$file"
                ;;
        "p")
                realpath -z "$file" | xsel -i -b
                notify-send 'Copied path to clipboard'
                ;;
        "r")
                name="$(rofi -dmenu -p  "rename $file to: ")" 2> /dev/null
                if ! [ -z "$name" ]; then
                    mv "$file" "$name"
                fi
                ;;
        esac
done
