services:

  microbin:
    image: ${MICROBIN_IMAGE:-danielszabo99/microbin:latest}
    container_name: microbin
    restart: unless-stopped
    environment:
      - MICROBIN_PUBLIC_PATH=https://paste.${MVR_AC:-mvr.ac}
      - MICROBIN_BIND=0.0.0.0
      - MICROBIN_PORT=8080
      - MICROBIN_TITLE=mandragora paste
      - MICROBIN_HIDE_FOOTER=true
      - MICROBIN_HIDE_HEADER=false
      - MICROBIN_HIDE_LOGO=false
      - MICROBIN_NO_LISTING=true
      - MICROBIN_HIGHLIGHTSYNTAX=true
      - MICROBIN_DEFAULT_EXPIRY=1day
      - MICROBIN_QR=true
    volumes:
      - ${MICROBIN_DATA_VOLUME:-./data}:/app/pasta_data
    networks:
      - seafile-net
    labels:
      caddy: https://paste.${MVR_AC:-mvr.ac}
      caddy.0_forward_auth: "authelia:9091"
      caddy.0_forward_auth.uri: "/api/authz/forward-auth"
      caddy.0_forward_auth.copy_headers: "Remote-User Remote-Groups Remote-Name Remote-Email"
      caddy.1_reverse_proxy: "{{upstreams 8080}}"

networks:
  seafile-net:
    external: true
