context.modules = [
  {   name = libpipewire-module-loopback
      args = {
          node.description = "Voice Morph Out"
          capture.props = {
              node.name = "voice_morph_sink"
              media.class = "Audio/Sink"
              audio.position = [ FL FR ]
              monitor.channel-volumes = true
          }
          playback.props = {
              node.name = "voice_morph_source"
              node.description = "Voice Morph Source"
              media.class = "Audio/Source/Virtual"
              audio.position = [ FL FR ]
          }
      }
  }
]
