j              add volume -2
k              add volume 2
ctrl+w         seek  1
ctrl+b         seek -1
c  no-osd sub-seek  1
C sub-reload 1
Ctrl+k     add video-zoom   0.1
Ctrl+j     add video-zoom  -0.1
PGUP ignore
PGDWN ignore
shift+h script-binding previousfile
shift+l script-binding nextfile
