ctrl+w         seek  1
ctrl+b         seek -1
C sub-reload 1
Ctrl+k     add video-zoom   0.1
Ctrl+j     add video-zoom  -0.1
PGUP ignore
PGDWN ignore
shift+h script-binding previousfile
shift+l script-binding nextfile
> playlist-next
< playlist-prev
\ no-osd cycle-values osd-level 3 1
r cycle-values loop-file "no" "inf"
0 seek 0 absolute ; set pause no
K add window-scale  0.01
J add window-scale -0.01
j cycle sub
k cycle sub down
w seek 4
W seek 16
b seek -4
B seek -16
ctrl+r cycle_values video-rotate "90" "180" "270" "0"
e ignore
s ignore
u ignore
1 ignore
2 ignore
3 ignore
4 ignore
5 ignore
6 ignore
7 ignore
8 ignore
9 ignore
V ignore
c ignore
Z ignore
t ignore
d ignore
R ignore
, ignore
/ ignore
