# Navigation
bind -n M-z select-pane -t :.+
bind h break-pane -d
bind Space run-shell "~/.local/bin/tmux_void.sh"
bind Enter run-shell "~/.local/bin/tmux_void_restore.sh"
bind l copy-mode
bind -r N previous-window
unbind d

bind -n -r C-q next-window
bind -n -r C-M-c new-window

# Resize panes
bind -r M-h resize-pane -L 2
bind -r M-j resize-pane -D 2
bind -r M-k resize-pane -U 2
bind -r M-l resize-pane -R 2

# Select panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
# bind -n M-l select-pane -R

# Splits
bind \\ split-window -c "#{pane_current_path}" -h
bind - split-window -c "#{pane_current_path}" -v

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

unbind '"'
unbind %
unbind [

# Pane join/send
bind  j command-prompt -p "join pane from:" "join-pane -s '%%'"
bind  o command-prompt -p "send pane to:"   "join-pane -t '%%'"

# Switch panes using Alt-arrow without prefix (Vim-aware)
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n M-Left  if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n M-Down  if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n M-Up    if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n M-Right if-shell "$is_vim" "send-keys C-l" "select-pane -U"

# Unbind Alt-number shortcuts before re-binding
unbind-key -n M-1
unbind-key -n M-2
unbind-key -n M-3
unbind-key -n M-4
unbind-key -n M-5
unbind-key -n M-6
unbind-key -n M-7
unbind-key -n M-8
unbind-key -n M-9

# Select pane by number
bind-key -n M-1 select-pane -t 0
bind-key -n M-2 select-pane -t 1
bind-key -n M-3 select-pane -t 2
bind-key -n M-4 select-pane -t 3
bind-key -n M-5 select-pane -t 4
bind-key -n M-6 select-pane -t 5
bind-key -n M-7 select-pane -t 6
bind-key -n M-8 select-pane -t 7
bind-key -n M-9 select-pane -t 8

# Select window by number
bind-key -n C-1 select-window -t 0
bind-key -n C-2 select-window -t 1
bind-key -n C-3 select-window -t 2
bind-key -n C-4 select-window -t 3
bind-key -n C-5 select-window -t 4
bind-key -n C-6 select-window -t 5
bind-key -n C-7 select-window -t 6
bind-key -n C-8 select-window -t 7
bind-key -n C-9 select-window -t 8

# Clipboard and Copy Mode
set -g set-clipboard on
# Detect if in WSL to use clip.exe
if-shell 'test -n "$WSL_DISTRO_NAME"' \
    "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'clip.exe'" \
    "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xsel -i -b'"
bind -T copy-mode-vi v send-keys -X begin-selection
