# TPM Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-urlview'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @open 'O'
set -g @open-editor 'o'
set -g @open-S 'https://www.google.com/search?q='

# Initialize TPM
run -b '~/.tmux/plugins/tpm/tpm'
run-shell '~/.tmux/plugins/tmux-open/open.tmux'
