set -g pane-active-border-style "bg=default fg=0"
set -g pane-border-style "bg=default fg=0"
set -g pane-active-border-style "fg=colour1,bg=default"

set -g status-left-length 100
set -g status-left "#[$_POWERLINE_SESSION_COLOR]#[$_POWERLINE_SESSION_HARD_DIVIDER_NEXT_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER#(env \"\$POWERLINE_COMMAND\" tmux left -R pane_id=\"`tmux display -p '#D'`\")"

set -g status off
