-- ./settings/simpleui/sui_settings.lua
return {
    ["simpleui_bar_enabled"] = true,
    ["simpleui_bar_mode"] = "both",
    ["simpleui_bar_tabs"] = {
        [1] = "home",
        [2] = "sui_settings",
        [3] = "homescreen",
        [4] = "history",
        [5] = "power",
    },
    ["simpleui_browsemeta_enabled"] = true,
    ["simpleui_enabled"] = true,
    ["simpleui_fc_cover_mode"] = "2_3",
    ["simpleui_fc_enabled"] = true,
    ["simpleui_fc_folder_style"] = "auto",
    ["simpleui_fc_subfolder_cover"] = true,
    ["simpleui_home_key_opens_hs"] = true,
    ["simpleui_hs_action_list_enabled"] = false,
    ["simpleui_hs_action_list_gap_pct"] = 100,
    ["simpleui_hs_action_list_items"] = {
        [1] = "sui_settings",
    },
    ["simpleui_hs_active_preset"] = "builtin_at_a_glance",
    ["simpleui_hs_clock_battery"] = false,
    ["simpleui_hs_clock_date"] = false,
    ["simpleui_hs_clock_enabled"] = true,
    ["simpleui_hs_collections_enabled"] = false,
    ["simpleui_hs_coverdeck_enabled"] = false,
    ["simpleui_hs_coverdeck_show_author"] = false,
    ["simpleui_hs_coverdeck_show_book_days"] = false,
    ["simpleui_hs_coverdeck_show_book_remaining"] = false,
    ["simpleui_hs_coverdeck_show_book_time"] = false,
    ["simpleui_hs_coverdeck_show_percent"] = true,
    ["simpleui_hs_coverdeck_show_progress"] = true,
    ["simpleui_hs_coverdeck_show_stats"] = true,
    ["simpleui_hs_coverdeck_show_title"] = true,
    ["simpleui_hs_currently_bar_style"] = "with_pct",
    ["simpleui_hs_currently_enabled"] = false,
    ["simpleui_hs_currently_show_author"] = true,
    ["simpleui_hs_currently_show_book_days"] = true,
    ["simpleui_hs_currently_show_book_remaining"] = true,
    ["simpleui_hs_currently_show_book_time"] = true,
    ["simpleui_hs_currently_show_description"] = true,
    ["simpleui_hs_currently_show_percent"] = false,
    ["simpleui_hs_currently_show_progress"] = true,
    ["simpleui_hs_currently_show_series"] = false,
    ["simpleui_hs_currently_show_title"] = true,
    ["simpleui_hs_currently_stats_style"] = "compact",
    ["simpleui_hs_flat_library_enabled"] = false,
    ["simpleui_hs_heatmap_enabled"] = false,
    ["simpleui_hs_module_order"] = {
        [1] = "clock",
        [2] = "quote",
        [3] = "spacer_row_529360",
        [4] = "quick_actions_row_248e20",
        [5] = "quick_actions_row_6a8c18",
        [6] = "currently",
        [7] = "recent",
        [8] = "new_books",
        [9] = "tbr",
        [10] = "coverdeck",
        [11] = "collections",
        [12] = "flat_library",
        [13] = "reading_goals",
        [14] = "reading_stats",
        [15] = "heatmap",
        [16] = "action_list",
    },
    ["simpleui_hs_new_books_enabled"] = false,
    ["simpleui_hs_qa_quick_actions_row_248e20_items"] = {
        [1] = "mandragora_status",
        [2] = "mandragora_portrait",
        [3] = "mandragora_sync",
        [4] = "bookmark_browser",
        [5] = "continue",
    },
    ["simpleui_hs_quick_actions_row_248e20_enabled"] = true,
    ["simpleui_hs_quick_actions_row_6a8c18_enabled"] = true,
    ["simpleui_hs_quote_enabled"] = true,
    ["simpleui_hs_reading_goals_enabled"] = false,
    ["simpleui_hs_reading_stats_enabled"] = false,
    ["simpleui_hs_recent_enabled"] = false,
    ["simpleui_hs_recent_show_finished"] = true,
    ["simpleui_hs_spacer_row_529360_enabled"] = true,
    ["simpleui_hs_spacer_row_529360_scale"] = 180,
    ["simpleui_hs_tbr_enabled"] = false,
    ["simpleui_layout"] = {
        ["pages"] = {
            [1] = {
                ["id"] = 1,
                ["modules"] = {
                    [1] = "clock",
                    [2] = "quote",
                    [3] = "spacer_row_529360",
                    [4] = "quick_actions_row_248e20",
                    [5] = "quick_actions_row_6a8c18",
                },
            },
        },
    },
    ["simpleui_loaded_version"] = "2.7.1",
    ["simpleui_navbar_transparent"] = false,
    ["simpleui_onboarding_done"] = true,
    ["simpleui_qa_list"] = {},
    ["simpleui_qa_migrated_v1"] = true,
    ["simpleui_qa_row_instances"] = {
        [1] = "quick_actions_row_248e20",
        [2] = "quick_actions_row_6a8c18",
    },
    ["simpleui_qs_bar_bg"] = "flat",
    ["simpleui_qs_bar_enabled"] = false,
    ["simpleui_qs_bar_frontlight"] = false,
    ["simpleui_qs_bar_settings_on_hold"] = true,
    ["simpleui_qs_bar_shape"] = "round",
    ["simpleui_qs_bar_slots"] = {
        [1] = "wifi_toggle",
        [2] = "bookmark_browser",
        [3] = "frontlight",
        [4] = "night_mode",
        [5] = "power",
        [6] = "sui_settings",
    },
    ["simpleui_qs_bar_warmth"] = false,
    ["simpleui_quote_deck_count"] = 99,
    ["simpleui_quote_deck_order"] = "6,76,78,95,72,71,18,83,49,22,93,31,36,47,45,54,19,43,67,3,62,97,77,86,37,60,17,27,99,9,10,96,48,81,87,28,75,1,42,26,29,33,66,13,51,40,24,34,25,56,90,7,84,65,38,98,64,21,88,20,92,74,12,53,70,80,4,57,2,41,59,89,44,16,50,14,35,94,46,55,91,30,23,82,15,61,85,5,11,52,39,68,32,63,8,73,58,69,79",
    ["simpleui_quote_deck_pos"] = 70,
    ["simpleui_reading_goals_show_annual"] = true,
    ["simpleui_reading_goals_show_daily"] = false,
    ["simpleui_reading_goals_show_monthly"] = false,
    ["simpleui_settings_migrated_v2"] = true,
    ["simpleui_settings_migrated_v3"] = true,
    ["simpleui_settings_migrated_v4"] = true,
    ["simpleui_settings_migrated_v5"] = true,
    ["simpleui_settings_migrated_v6"] = true,
    ["simpleui_settings_migrated_v7"] = true,
    ["simpleui_settings_migrated_v8"] = true,
    ["simpleui_spacer_row_instances"] = {
        [1] = "spacer_row_529360",
    },
    ["simpleui_stale_books_v1"] = {
        ["prefetched_data"] = {
            ["/mnt/us/koreader/help/quickstart-en-v2026.07.1.html"] = {
                ["doc_pages"] = 8,
                ["partial_md5_checksum"] = "f57f1d89ea1f37a9c43b68371cb7899d",
                ["percent"] = 1,
                ["stat_pages"] = 8,
                ["summary"] = {
                    ["modified"] = "2026-09-12",
                    ["status"] = "reading",
                },
                ["title"] = "KOReader Quickstart Guide",
            },
        },
        ["recent_fps"] = {
            [1] = "/mnt/us/koreader/help/quickstart-en-v2026.07.1.html",
        },
    },
    ["simpleui_statusbar_transparent"] = false,
    ["simpleui_streak_freeze_last_total_secs"] = 171,
    ["simpleui_streak_freeze_watermark"] = 1,
    ["simpleui_style_wallpaper"] = "/mnt/us/mandragora/art/0kdtlfpbc0u61-2748130165.png",
    ["simpleui_style_wallpaper_enabled"] = false,
    ["simpleui_style_wallpaper_opacity"] = 0,
    ["simpleui_tb_fm_cfg"] = {
        ["order_left"] = {
            [1] = "fm_back",
            [2] = "fm_search",
        },
        ["order_right"] = {
            [1] = "fm_browse",
            [2] = "fm_menu",
        },
        ["side"] = {
            ["fm_back"] = "left",
            ["fm_browse"] = "right",
            ["fm_menu"] = "right",
            ["fm_search"] = "left",
        },
    },
    ["simpleui_tb_item_fm_browse"] = true,
    ["simpleui_tb_item_fm_search"] = true,
    ["simpleui_topbar_config"] = {
        ["order_left"] = {
            [1] = "clock",
        },
        ["order_right"] = {
            [1] = "wifi",
            [2] = "battery",
        },
        ["side"] = {
            ["battery"] = "right",
            ["clock"] = "left",
            ["wifi"] = "right",
        },
    },
    ["simpleui_topbar_enabled"] = true,
    ["simpleui_updater_auto_check"] = true,
    ["simpleui_wallpaper_show_in_fm"] = false,
}
