[General]
ScreenWidth=1920
ScreenHeight=1080
ScreenPadding=

Font=Iosevka Nerd Font Mono
FontSize=13

KeyboardSize=0.4

RoundCorners=16

Locale=
HourFormat=HH:mm
DateFormat=dddd, MMMM d

HeaderText=

BackgroundPlaceholder=Backgrounds/hyprland_kath.png
Background=Backgrounds/hyprland_kath.mp4
BackgroundSpeed=1.0
PauseBackground=
DimBackground=0.15
CropBackground=true
BackgroundHorizontalAlignment=center
BackgroundVerticalAlignment=center

HeaderTextColor=#cdd6f4
DateTextColor=#cdd6f4
TimeTextColor=#cdd6f4

FormBackgroundColor=#11111b
BackgroundColor=#1e1e2e
DimBackgroundColor=#11111b

LoginFieldBackgroundColor=#181825
PasswordFieldBackgroundColor=#181825
LoginFieldTextColor=#cdd6f4
PasswordFieldTextColor=#cdd6f4
UserIconColor=#89b4fa
PasswordIconColor=#89b4fa

PlaceholderTextColor=#6c7086
WarningColor=#f38ba8

LoginButtonTextColor=#11111b
LoginButtonBackgroundColor=#89b4fa
SystemButtonsIconsColor=#cdd6f4
SessionButtonTextColor=#cdd6f4
VirtualKeyboardButtonTextColor=#cdd6f4

DropdownTextColor=#cdd6f4
DropdownSelectedBackgroundColor=#89b4fa
DropdownBackgroundColor=#181825

HighlightTextColor=#11111b
HighlightBackgroundColor=#89b4fa
HighlightBorderColor=transparent

HoverUserIconColor=#b4befe
HoverPasswordIconColor=#b4befe
HoverSystemButtonsIconsColor=#b4befe
HoverSessionButtonTextColor=#b4befe
HoverVirtualKeyboardButtonTextColor=#b4befe

PartialBlur=true
FullBlur=
BlurMax=48
Blur=2.5

HaveFormBackground=true
FormPosition=center

VirtualKeyboardPosition=center

HideVirtualKeyboard=false
HideSystemButtons=false
HideLoginButton=false

ForceLastUser=true
PasswordFocus=true
HideCompletePassword=true
AllowEmptyPassword=false
AllowUppercaseLettersInUsernames=false
BypassSystemButtonsChecks=false
RightToLeftLayout=false

TranslatePlaceholderUsername=
TranslatePlaceholderPassword=
TranslateLogin=
TranslateLoginFailedWarning=
TranslateCapslockWarning=
TranslateSuspend=
TranslateHibernate=
TranslateReboot=
TranslateShutdown=
TranslateSessionSelection=
TranslateVirtualKeyboardButtonOn=
TranslateVirtualKeyboardButtonOff=
