#!/bin/sh
wal -a 299 -i "`cat $HOME/.cache/wal/wal`"
sshfs opc@oracle:/home/opc/drive oracle 
pgrep -x compton             || $_ -D 3 --blur-strength 10 --blur-method kawase -b --dbus &
pgrep -x polybar             || $_   &
pgrep -x mpd                 || $_   &
pgrep -x sxhkd               || $_   &
pgrep -x ntfd                || $_   &
pgrep -f cleanfullscreen     || nohup /home/m/.local/bin/cleanfullscreen 2>&1 > /dev/null &
pgrep -f mpd-discord-rpc     || (sleep 10 && nohup /home/m/.cargo/bin/mpd-discord-rpc > /dev/null 2>&1 &)
pgrep -f twitch-indicator    || nohup /usr/bin/twitch-indicator 2>&1 > /dev/null &
pgrep -f kdeconnectd         || nohup /usr/bin/kdeconnectd 2>&1 > /dev/null &
pgrep -f keyledsd            || nohup /usr/bin/keyledsd 2>&1 > /dev/null &
pgrep -f desktop_switcher    || nohup /home/m/.local/bin/desktop_switcher 2>&1 > /dev/null &


bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX XXI XXII XXIII XXIV XXV XXVI XXVII XXVIII XXIX XXX XXXI XXXII XXXIII XXXIV XXXV XXXVI XXXVII XXXVIII XXXIX XL

bspc config border_width          0
bspc config window_gap            12
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

bspc   rule   -a   whats-app-nativefier-d52542 desktop=^4
bspc   rule   -a   jetbrains-idea-ce           desktop=^8  follow=true
bspc   rule   -a   jetbrains-studio            desktop=^8  follow=true
bspc   rule   -a   jetbrains-pycharm-ce        desktop=^8  follow=true
bspc   rule   -a   Code                        desktop=^8  follow=true
bspc   rule   -a   Slack                       desktop=^9
bspc   rule   -a   beekeeper-studio            desktop=^11 follow=true
bspc   rule   -a   Gdmap                       desktop=^11 follow=true
bspc   rule   -a   Postman                     desktop=^13
bspc   rule   -a   Zathura                     desktop=^19 follow=true state=tiled
bspc   rule   -a   mpv                                                 state=floating
bspc   rule   -a   Mysql-workbench-bin         desktop=^11 follow=true
bspc   rule   -a   "MongoDB Compass"           desktop=^11 follow=true
bspc config external_rules_command $HOME/.config/bspwm/external_rules
bspc desktop -f ^1
