#!/bin/sh
wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

# notify-send $title

if [ "$title" = _zsh_ ] ; then
	echo "desktop=^3"
fi

if [ "$title" = _ranger_ ] ; then
	echo "desktop=^2"
fi

if [ "$title" = _tmux-float_ ] ; then
	echo state=floating rectangle=400x300+1000+500
fi
