#!/bin/sh
wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

# notify-send "$title"
# notify-send "$class"

if [ "$title" = "Tor Browser" ]; then
	echo "desktop=^22 follow=true"
fi

if [ "$title" = Steam ]; then
	echo "desktop=^15 follow=true"
fi

if [ "$title" = Nibbler ]; then
	echo "desktop=^20"
fi

if [ "$title" = _visualizer-float_ ]; then
	echo state=floating rectangle=500x400+1400+630 sticky=on
fi

if [ "$title" = _neomutt_ ]; then
	echo "desktop=^12"
fi

if [ "$title" = "Mozilla Thunderbird" ]; then
	echo "desktop=^12 follow=true" 
fi

if [ "$title" = _zsh_ ]; then
	echo "desktop=^3; "
fi

if [ "$title" = _ranger_ ]; then
	echo "desktop=^2"
fi

if [ "$class" = TelegramDesktop ]; then
	echo "desktop=^5 follow=true"
fi

if [ "$title" = WhatsAppWeb ]; then
	echo "desktop=^4 follow=true"
fi

if [ "$class" = discord ]; then
	echo "desktop=^17 follow=true"
fi

if [ "$class" = firefox ]; then
	[[ `pgrep -f firefox | wc -l` -gt 1 ]] && echo "desktop=^1"
fi

if [ "$title" = _tmux-float_ ]; then
	echo state=floating rectangle=400x300+1500+670 sticky=on
fi

if [ "$class" = kmag ]; then
	echo state=floating rectangle=400x300+1500+670 sticky=on
fi

if [ "$class" = Org.gnome.Weather ]; then
	echo state=floating rectangle=400x300+1160+470 sticky=on
fi

if [ "$class" = globoplay-assista-tv-globo-ao-vivo-nativefier-529bf2 ] ; then
	echo state=floating rectangle=550x300+1358+738 sticky=on
fi
