---
theme: dark

server:
  address: 'tcp://0.0.0.0:9091'
  buffers:
    read: 4096
    write: 4096

log:
  level: info
  format: text

totp:
  disable: false
  issuer: 'mvr.ac'
  algorithm: 'SHA1'
  digits: 6
  period: 30

webauthn:
  disable: true

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: '5m'
  file:
    path: '/config/users_database.yml'
    watch: true
    password:
      algorithm: 'argon2'
      argon2:
        variant: 'argon2id'
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

password_policy:
  standard:
    enabled: true
    min_length: 12
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: false

session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '1h'
  expiration: '12h'
  remember_me: '1M'
  cookies:
    - domain: 'mvr.ac'
      authelia_url: 'https://auth.mvr.ac'
      default_redirection_url: 'https://hub.mvr.ac'
  redis:
    host: 'authelia-redis'
    port: 6379

storage:
  local:
    path: '/data/db.sqlite3'

regulation:
  max_retries: 3
  find_time: '2m'
  ban_time: '15m'

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'auth.mvr.ac'
      policy: 'bypass'
    - domain: ['grafana.mvr.ac', 'term.mvr.ac', 'paste.mvr.ac']
      policy: 'two_factor'

notifier:
  filesystem:
    filename: '/data/notifications.txt'

telemetry:
  metrics:
    enabled: false
