$wallpaper = {{image}}

$foreground = {{colors.on_surface.default.rgba}}
$background = {{colors.surface.default.rgba}}

$color0 = {{colors.surface.default.rgba}}
$color1 = {{colors.primary.default.rgba}}
$color2 = {{colors.secondary.default.rgba}}
$color3 = {{colors.tertiary.default.rgba}}
$color4 = {{colors.primary_container.default.rgba}}
$color5 = {{colors.secondary_container.default.rgba}}
$color6 = {{colors.tertiary_container.default.rgba}}
$color7 = {{colors.on_surface.default.rgba}}
$color8 = {{colors.surface_variant.default.rgba}}
$color9 = {{colors.primary_fixed.default.rgba}}
$color10 = {{colors.secondary_fixed.default.rgba}}
$color11 = {{colors.tertiary_fixed.default.rgba}}
$color12 = {{colors.primary_fixed_dim.default.rgba}}
$color13 = {{colors.secondary_fixed_dim.default.rgba}}
$color14 = {{colors.tertiary_fixed_dim.default.rgba}}
$color15 = {{colors.on_surface_variant.default.rgba}}
