set -g @wal_bg "{{colors.surface.default.hex}}"
set -g @wal_fg "{{colors.on_surface.default.hex}}"
set -g @wal_accent "{{colors.primary_container.default.hex}}"
set -g @wal_accent_fg "{{colors.surface.default.hex}}"
set -g @wal_dim "{{colors.surface_variant.default.hex}}"
set -g @wal_dim_fg "{{colors.on_surface.default.hex}}"
set -g @wal_mark "{{colors.tertiary_container.default.hex}}"
set -g @wal_mark_fg "{{colors.on_tertiary_container.default.hex}}"
