so $HOME/.config/nvim/settings.vim
so $HOME/.config/nvim/functions.vim
so $HOME/.config/nvim/let.vim
so $HOME/.config/nvim/commands.vim
so $HOME/.config/nvim/autocommands.vim
so $HOME/.config/nvim/general.vim
so $HOME/.config/nvim/plug.vim
so $HOME/.config/nvim/map.vim
so $HOME/.config/nvim/post-init.vim
