monitor.bluez.properties = {
  bluez5.roles = [ a2dp-sink a2dp-source ]
  bluez5.codecs = [ sbc ]
  bluez5.enable-msbc = false
  bluez5.enable-hw-volume = true
}

monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        node.latency = 1024/48000
        bluez5.a2dp.bitpool-min = 32
        bluez5.a2dp.bitpool-max = 53
        # Lower priority to avoid preempting critical tasks if the driver is struggling
        priority.driver = 1000
        priority.session = 1000
      }
    }
  }
]
