monitor.bluez.properties = {
  bluez5.roles = [ a2dp-sink a2dp-source ]
  bluez5.enable-msbc = false
  bluez5.enable-hw-volume = true
}

monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        node.latency = 1024/48000
      }
    }
  }
]
