monitor.bluez.rules = [
  {
    matches = [
      { device.name = "bluez_card.04_57_91_D1_38_20" }
    ]
    actions = {
      update-props = {
        device.profile = "headset-head-unit"
        bluez5.auto-connect = [ hfp_hf hsp_hs a2dp_sink ]
      }
    }
  }
]
